version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: python -m pip install --upgrade pip
      - run: pip install nox==2020.12.31
      - run: nox


workflows:
  build_and_test:
    jobs:
      - test