version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: pip install nox
      - run: poetry install
      - run: nox


workflows:
  build_and_test:
    jobs:
      - test